In [1]:
import pandas as pd
import numpy as np

In [57]:
# 1d and 2D array
oneD = np.array([1,2,3,])
twoD = np.array([[1,2,3],[4,5,6]])


In [58]:
# one and zero and reshape
ones = np.ones((2,3))
zeros = np.zeros((3,3))


In [59]:
# random 
random_val = np.random.random((3,4))
random_val

array([[0.60793577, 0.37773191, 0.17436608, 0.1550198 ],
       [0.08886179, 0.29336043, 0.86524284, 0.92241715],
       [0.53402909, 0.2904355 , 0.76517819, 0.75824644]])

In [60]:
# linespace
print(np.linspace(1,10,8))

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [61]:
# identity
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
# dtype  and change dtpye
array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array.dtype
array.astype(dtype='float64')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [63]:
# arthmitic operations 
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)

In [64]:
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(b,a)
np.power(a,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]])

In [66]:
# transpose mix and min
array = (np.random.random((3,3))*100).round(2)
array

array([[79.4 , 39.71, 98.28],
       [10.18, 60.89, 96.33],
       [15.55, 95.36, 87.88]])

In [74]:
np.min(array,axis=0)
np.max(array,axis=1)
np.transpose(array)

array([[79.4 , 10.18, 15.55],
       [39.71, 60.89, 95.36],
       [98.28, 96.33, 87.88]])

In [11]:
# advance indexing
array = np.arange(24).reshape(4,6)
array[[2,3]]
array[:,[0,1,2]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20]])

In [ ]:
array = np.random.randint(1,100,18).reshape(6,3)


array([[42, 45, 69],
       [94, 85, 17],
       [95, 58, 72],
       [99, 94, 64],
       [60, 13, 83],
       [27, 11, 26]], dtype=int32)

In [14]:
array[array>30]

array([42, 45, 69, 94, 85, 95, 58, 72, 99, 94, 64, 60, 83], dtype=int32)

In [ ]:
# sort method by rows and columns
np.sort(array,axis=0)

array([[27, 11, 17],
       [42, 13, 26],
       [60, 45, 64],
       [94, 58, 69],
       [95, 85, 72],
       [99, 94, 83]], dtype=int32)

In [25]:
# concatenating
array1 = np.arange(9).reshape(3,3)
array2 = np.arange(9,18).reshape(3,3)
np.concatenate((array1,array2),axis=1)

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

In [26]:
# Key Concept: Extracting unique elements
# Unique: np.unique() returns sorted unique elements, removing duplicates
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
print("\nArray with duplicates:", e)
print("Unique values:", np.unique(e))


Array with duplicates: [1 1 2 2 3 3 4 4 5 5 6 6]
Unique values: [1 2 3 4 5 6]


In [27]:
# Key Concept: Expanding array dimensions
# Expand dims: np.expand_dims() adds a new axis, changing array shape (e.g., 1D to 2D)
arr = np.arange(1, 25)
print("\nOriginal array:", arr)
print("Original shape:", arr.shape)
print("Shape after expand_dims:", np.expand_dims(arr, axis=1).shape)  # Add column dimension

# Key Concept: Conditional indexing and replacement
# Where: np.where() finds indices or replaces values based on a condition
print("\nIndices where arr > 19:", np.where(arr > 19))  # Indices of values > 19
print("Indices where arr is even:", np.where(arr % 2 == 0))  # Indices of even numbers
print("Replace arr > 6 with 0:", np.where(arr > 6, 0, arr))  # Replace >6 with 0
print("Replace even numbers with 0:", np.where(arr % 2 == 0, 0, arr))  # Replace evens with 0


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Original shape: (24,)
Shape after expand_dims: (24, 1)

Indices where arr > 19: (array([19, 20, 21, 22, 23]),)
Indices where arr is even: (array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]),)
Replace arr > 6 with 0: [1 2 3 4 5 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Replace even numbers with 0: [ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0 21  0 23  0]


In [28]:
# Key Concept: Finding indices of max/min values
# Argmax/Argmin: np.argmax() and np.argmin() return indices of max and min values
print("\nIndex of maximum value:", np.argmax(arr))
print(f"Index of minimum value: {np.argmin(arr)}")


Index of maximum value: 23
Index of minimum value: 0


In [29]:
# Key Concept: Calculating percentiles
# Percentile: np.percentile() computes the nth percentile (e.g., median at 50%)
print("\nOriginal array:", arr)
print(f"50th percentile (median): {np.percentile(arr, 50)}")



Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
50th percentile (median): 12.5
